import React from "react";
import { Box, Typography, Paper, IconButton, Chip } from "@mui/material";
import InsertDriveFileOutlinedIcon from "@mui/icons-material/InsertDriveFileOutlined";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import DownloadOutlinedIcon from "@mui/icons-material/DownloadOutlined";
import CheckCircleOutlineIcon from "@mui/icons-material/CheckCircleOutline";
import { FiEdit } from "react-icons/fi";
function GeneratedDocumentSection() {
  const documents = [
    {
      type: "Offer Letter",
      size: "245 KB",
      employee: "Rahul Sharma",
      id: "EMP001",
      company: "Nimbja Security",
      generatedBy: "Aditi Khade",
      date: "Feb 15, 2026",
    },
    {
      type: "Salary Slip",
      size: "189 KB",
      employee: "Priya Patel",
      id: "EMP002",
      company: "Penta Software",
      generatedBy: "Aditi Khade",
      date: "Feb 14, 2026",
    },
    {
      type: "Appointment Letter",
      size: "267 KB",
      employee: "Amit Kumar",
      id: "EMP003",
      company: "Quick Management",
      generatedBy: "Aditi Khade",
      date: "Feb 13, 2026",
    },
    {
      type: "Experience Letter",
      size: "198 KB",
      employee: "Sneha Reddy",
      id: "EMP004",
      company: "Smart Software",
      generatedBy: "Aditi Khade",
      date: "Feb 12, 2026",
    },
    {
      type: "Relieving Letter",
      size: "212 KB",
      employee: "Vikram Singh",
      id: "EMP005",
      company: "Cubeage Tech",
      generatedBy: "Aditi Khade",
      date: "Feb 11, 2026",
    },
    {
      type: "Increment Letter",
      size: "223 KB",
      employee: "Anita Desai",
      id: "EMP006",
      company: "Neweage Cloud",
      generatedBy: "Aditi Khade",
      date: "Feb 10, 2026",
    },
  ];

  return (
    <Box sx={{ width: "100%", mt: 4 }}>
      {/* Heading */}
      <Typography
        sx={{
          fontSize: "20px",
          fontWeight: 600,
          color: "#1F2937",
          mb: 3,
        }}
      >
        Today’s generated documents
      </Typography>

      <Paper
        sx={{
          borderRadius: "16px",
          boxShadow: "0px 20px 50px rgba(0,0,0,0.06)",
          overflow: "hidden",
        }}
      >
        {/* Horizontal Scroll Wrapper */}
        <Box sx={{ overflowX: "auto" }}>
          <Box sx={{ minWidth: 1100 }}>
            {/* Header */}
            <Box
              sx={{
                display: "grid",
                gridTemplateColumns: "2fr 1.4fr 1.4fr 1.2fr 1fr 1fr 1fr",
                backgroundColor: "#ebecf9",
                px: 4,
                py: 2,
                fontSize: "13px",
                fontWeight: 500,
                color: "#6B7280",
              }}
            >
              <Box>Document Type</Box>
              <Box>Employee</Box>
              <Box>Company</Box>
              <Box>Generated by</Box>
              <Box>Date</Box>
              <Box>Status</Box>
              <Box textAlign="center">Actions</Box>
            </Box>

            {/* Rows */}
            {documents.map((item, index) => (
              <Box
                key={index}
                sx={{
                  display: "grid",
                  gridTemplateColumns: "2fr 1.4fr 1.4fr 1.2fr 1fr 1fr 1fr",
                  px: 4,
                  py: 3,
                  alignItems: "center",
                  borderTop: "1px solid #F1F1F4",
                  "&:hover": {
                    backgroundColor: "#f9fafb",
                  },
                }}
              >
                {/* Document Type */}
                <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
                  <Box
                    sx={{
                      width: 40,
                      height: 40,
                      borderRadius: "12px",
                      background:
                        "linear-gradient(to bottom right, #393B8B, #AD78D2)",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      color: "#fff",
                    }}
                  >
                    <InsertDriveFileOutlinedIcon fontSize="small" />
                  </Box>

                  <Box>
                    <Typography
                      sx={{
                        fontSize: "14px",
                        fontWeight: 500,
                        color: "#1F2937",
                      }}
                    >
                      {item.type}
                    </Typography>
                    <Typography
                      sx={{
                        fontSize: "12px",
                        color: "#9CA3AF",
                      }}
                    >
                      {item.size}
                    </Typography>
                  </Box>
                </Box>

                {/* Employee */}
                <Box>
                  <Typography
                    sx={{
                      fontSize: "14px",
                      fontWeight: 500,
                      color: "#1F2937",
                    }}
                  >
                    {item.employee}
                  </Typography>
                  <Typography
                    sx={{
                      fontSize: "12px",
                      color: "#9CA3AF",
                    }}
                  >
                    {item.id}
                  </Typography>
                </Box>

                {/* Company */}
                <Typography sx={{ fontSize: "14px", color: "#4B5563" }}>
                  {item.company}
                </Typography>

                {/* Generated By */}
                <Typography
                  sx={{
                    fontSize: "14px",
                    fontWeight: 500,
                    color: "#374151",
                  }}
                >
                  {item.generatedBy}
                </Typography>

                {/* Date */}
                <Typography sx={{ fontSize: "14px", color: "#6B7280" }}>
                  {item.date}
                </Typography>

                {/* Status */}
                <Box>
                  <Chip
                    icon={
                      <CheckCircleOutlineIcon
                        sx={{ fontSize: 16, color: "#16A34A" }}
                      />
                    }
                    label="Completed"
                    sx={{
                      backgroundColor: "#DCFCE7",
                      color: "#16A34A",
                      fontSize: "12px",
                      fontWeight: 500,
                      borderRadius: "20px",
                    }}
                  />
                </Box>

                {/* Actions */}
                <Box sx={{ display: "flex", justifyContent: "center", gap: 1 }}>
                  {/* View */}
                  <IconButton
                    sx={{
                      width: 36,
                      height: 36,
                      borderRadius: "8px",
                      backgroundColor: "#EEF2FF",
                      "&:hover": { backgroundColor: "#E0E7FF" },
                    }}
                  >
                    <VisibilityOutlinedIcon
                      sx={{ fontSize: 18, color: "#6366F1" }}
                    />
                  </IconButton>

                  {/* Edit */}
                  <IconButton
                    sx={{
                      width: 36,
                      height: 36,
                      borderRadius: "8px",
                      backgroundColor: "#FEF3C7",
                      "&:hover": { backgroundColor: "#FDE68A" },
                    }}
                  >
                    <FiEdit style={{ fontSize: 18, color: "#F59E0B" }} />
                  </IconButton>

                  {/* Download */}
                  <IconButton
                    sx={{
                      width: 36,
                      height: 36,
                      borderRadius: "8px",
                      backgroundColor: "#ECFDF5",
                      "&:hover": { backgroundColor: "#D1FAE5" },
                    }}
                  >
                    <DownloadOutlinedIcon
                      sx={{ fontSize: 18, color: "#22C55E" }}
                    />
                  </IconButton>
                </Box>
              </Box>
            ))}
          </Box>
        </Box>
      </Paper>
    </Box>
  );
}

export default GeneratedDocumentSection;
