import React, { useEffect, useState } from "react";
import {
  Box,
  Typography,
  Paper,
  IconButton,
  Chip,
  Pagination,
} from "@mui/material";
import InsertDriveFileOutlinedIcon from "@mui/icons-material/InsertDriveFileOutlined";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import DownloadOutlinedIcon from "@mui/icons-material/DownloadOutlined";
import CheckCircleOutlineIcon from "@mui/icons-material/CheckCircleOutline";
import { FiEdit } from "react-icons/fi";
import { useNavigate } from "react-router-dom";
import { toCamelCase } from "../../../utils/textFormat.js";

import ROUTES from "../../../core/constants/routes.constant";
import ApiService from "../../../core/services/api.service";
import ServerUrl from "../../../core/constants/serverURL.constant";

function GeneratedDocumentSection() {
  const navigate = useNavigate();
  const api = new ApiService();

  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const rowsPerPage = 10;
  const [totalCount, setTotalCount] = useState(0);
  // 🔥 Fetch documents from backend
  const fetchDocuments = async (currentPage = 1) => {
    try {
      setLoading(true);

      const res = await api.apiget(
        `${ServerUrl.API_ALL_DOCUMENTS}?page=${currentPage}`,
      );

      console.log("API RESPONSE:", res);

      // ✅ Correct mapping based on your API
      const docs = res?.data || [];
      const totalPages = res?.pages || 1;

      const normalizedDocs = docs.map((item) => ({
        ...item,
        employeeName: toCamelCase(item.employeeName),
        company: toCamelCase(item.company),
        issuedTo: toCamelCase(item.issuedTo),
      }));
      const total = res?.total || 0;
      setTotalCount(total);
      setDocuments(normalizedDocs);
      setTotalPages(totalPages);
    } catch (error) {
      console.error("Error fetching documents:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDocuments(page);
  }, [page]);

  return (
    <Box sx={{ width: "100%", mt: 4 }}>
      <Typography
        sx={{
          fontSize: "20px",
          fontWeight: 600,
          color: "#1F2937",
          mb: 3,
        }}
      >
        Today’s generated documents
      </Typography>

      <Paper
        sx={{
          borderRadius: "16px",
          boxShadow: "0px 20px 50px rgba(0,0,0,0.06)",
          overflow: "hidden",
        }}
      >
        <Box sx={{ overflowX: "auto" }}>
          <Box sx={{ minWidth: 1100 }}>
            {/* Header */}
            <Box
              sx={{
                display: "grid",
                gridTemplateColumns: "1.8fr 1.5fr 2.1fr 1.8fr 1fr 1fr 1fr",
                backgroundColor: "#ebecf9",
                px: 4,
                py: 2,
                fontSize: "13px",
                fontWeight: 500,
                color: "#6B7280",
              }}
            >
              <Box>Document Type</Box>
              <Box>Employee</Box>

              <Box>Company</Box>

              <Box>Generated by</Box>

              <Box>Date</Box>
              <Box>Status</Box>
              <Box textAlign="center">Actions</Box>
            </Box>

            {/* 🔥 Loading */}
            {loading && (
              <Box sx={{ p: 4, textAlign: "center" }}>Loading documents...</Box>
            )}

            {/* 🔥 No Data */}
            {!loading && totalCount === 0 && (
              <Box sx={{ p: 4, textAlign: "center" }}>No documents found</Box>
            )}

            {/* 🔥 Dynamic Rows */}
            {!loading &&
              documents.map((item, index) => (
                <Box
                  key={index}
                  onClick={() =>
                    navigate(ROUTES.USERDOCUMENT_DETAIL, {
                      state: {
                        document: item,
                      },
                    })
                  }
                  sx={{
                    display: "grid",
                    gridTemplateColumns: "1.8fr 1.5fr 2.2fr 1.8fr 1fr 1fr 1fr",
                    px: 4,
                    py: 3,
                    alignItems: "center",
                    borderTop: "1px solid #F1F1F4",
                    cursor: "pointer",
                    "&:hover": {
                      backgroundColor: "#f9fafb",
                    },
                  }}
                >
                  {/* Document Type */}
                  <Box
                    sx={{
                      width: "100%",
                      display: "flex",
                      alignItems: "center",
                      gap: 2,
                    }}
                  >
                    <Box
                      sx={{
                        width: 40,
                        height: 40,
                        borderRadius: "12px",
                        background:
                          "linear-gradient(to bottom right, #393B8B, #AD78D2)",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        color: "#fff",
                      }}
                    >
                      <InsertDriveFileOutlinedIcon fontSize="small" />
                    </Box>

                    <Box>
                      <Typography sx={{ fontSize: "14px", fontWeight: 500 }}>
                        {item.documentType || "Document"}
                      </Typography>
                      {/* <Typography sx={{ fontSize: "12px", color: "#9CA3AF" }}>
                        {item.size || "—"}
                      </Typography> */}
                    </Box>
                  </Box>

                  {/* Employee */}
                  <Box>
                    <Typography sx={{ fontSize: "14px", fontWeight: 500 }}>
                      {item.employeeName || item.employee || "—"}
                    </Typography>
                    <Typography sx={{ fontSize: "12px", color: "#9CA3AF" }}>
                      {item.employeeId || item.id || "—"}
                    </Typography>
                  </Box>

                  {/* Company */}
                  <Typography
                    sx={{
                      fontSize: "14px",
                      whiteSpace: "normal",
                      wordBreak: "break-word",
                      display: "-webkit-box",
                      WebkitLineClamp: 2,
                      WebkitBoxOrient: "vertical",
                      overflow: "hidden",
                      pr: 2,
                    }}
                  >
                    {item.company || "—"}
                  </Typography>

                  {/* Generated By */}
                  <Typography
                    sx={{
                      fontSize: "14px",
                      whiteSpace: "normal",
                      wordBreak: "break-word",
                      display: "-webkit-box",
                      WebkitLineClamp: 2,
                      WebkitBoxOrient: "vertical",
                      overflow: "hidden",
                      pr: 2,
                      color: "#4B5563",
                    }}
                  >
                    {item.issuedTo || "—"}
                  </Typography>

                  {/* Date */}
                  <Typography sx={{ fontSize: "14px" }}>
                    {item.createdAt
                      ? new Date(item.createdAt).toLocaleDateString("en-US", {
                          month: "short",
                          day: "numeric",
                          year: "numeric",
                        })
                      : item.date || "—"}
                  </Typography>

                  {/* Status */}
                  <Box>
                    <Chip
                      icon={
                        <CheckCircleOutlineIcon
                          sx={{
                            backgroundColor: "#DCFCE7",
                            fontSize: 18,
                            color: "#15803D",
                          }}
                        />
                      }
                      label={item.paymentStatus || "Completed"}
                      sx={{
                        backgroundColor: "#DCFCE7",
                        color: "#15803D",
                        fontWeight: 500,
                        fontSize: "13px",
                        px: 1,
                        py: 0.5,
                        // borderRadius: "999px",
                        height: "36px",
                        "& .MuiChip-icon": {
                          marginLeft: "8px",
                        },
                        "& .MuiChip-label": {
                          paddingRight: "12px",
                        },
                      }}
                    />
                  </Box>

                  {/* Actions */}
                  <Box
                    sx={{ display: "flex", justifyContent: "center", gap: 1 }}
                  >
                    {/* Edit */}
                    <IconButton
                      onClick={(e) => {
                        e.stopPropagation();

                        navigate(ROUTES.EDIT_DOCUMENT, {
                          state: { document: item },
                        });
                      }}
                      sx={{
                        backgroundColor: "#FEF3C7",
                        borderRadius: "12px",
                        width: 36,
                        height: 36,
                        "&:hover": {
                          backgroundColor: "#FDE68A",
                        },
                      }}
                    >
                      <FiEdit size={16} color="#D97706" />
                    </IconButton>

                    {/* View */}
                    <IconButton
                      onClick={(e) => {
                        e.stopPropagation();

                        navigate(ROUTES.USERDOCUMENT_DETAIL, {
                          state: { documentId: item._id },
                        });
                      }}
                      sx={{
                        backgroundColor: "#E0E7FF",
                        borderRadius: "12px",
                        width: 36,
                        height: 36,
                        "&:hover": {
                          backgroundColor: "#C7D2FE",
                        },
                      }}
                    >
                      <VisibilityOutlinedIcon
                        sx={{ fontSize: 18, color: "#4F46E5" }}
                      />
                    </IconButton>

                    {/* Download */}
                    <IconButton
                      onClick={async (e) => {
                        e.stopPropagation();

                        try {
                          const response = await api.apiget(
                            `/offer-letter/download/${item._id}`,
                            { responseType: "blob" },
                          );

                          const url = window.URL.createObjectURL(
                            new Blob([response]),
                          );
                          const link = document.createElement("a");
                          link.href = url;
                          link.setAttribute(
                            "download",
                            `${item.employeeName}.pdf`,
                          );
                          document.body.appendChild(link);
                          link.click();
                        } catch (err) {
                          console.error("Download failed", err);
                        }
                      }}
                      sx={{
                        backgroundColor: "#DCFCE7",
                        borderRadius: "12px",
                        width: 36,
                        height: 36,
                        "&:hover": {
                          backgroundColor: "#BBF7D0",
                        },
                      }}
                    >
                      <DownloadOutlinedIcon
                        sx={{ fontSize: 18, color: "#16A34A" }}
                      />
                    </IconButton>
                  </Box>
                </Box>
              ))}
          </Box>
        </Box>
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            px: 4,
            py: 2.5,
            borderTop: "1px solid #F1F1F4",
            backgroundColor: "#fff",
          }}
        >
          {/* LEFT INFO */}
          <Typography
            sx={{
              fontSize: "13px",
              color: "#6B7280",
              fontWeight: 500,
            }}
          >
            Showing {(page - 1) * rowsPerPage + 1}–
            {Math.min(page * rowsPerPage, totalCount)} of {totalCount} results
          </Typography>

          {/* RIGHT CONTROLS */}
          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              gap: 1,
              backgroundColor: "#F9FAFB",
              borderRadius: "12px",
              p: "4px",
            }}
          >
            {/* PREV */}
            <Box
              onClick={() => page > 1 && setPage(page - 1)}
              sx={{
                px: 2,
                py: "6px",
                borderRadius: "8px",
                cursor: page === 1 ? "not-allowed" : "pointer",
                color: page === 1 ? "#9CA3AF" : "#374151",
                fontSize: "13px",
                fontWeight: 500,
                "&:hover": {
                  backgroundColor: page === 1 ? "transparent" : "#E5E7EB",
                },
              }}
            >
              Prev
            </Box>

            {/* PAGE NUMBERS */}
            {[...Array(totalPages)].map((_, i) => {
              const pageNum = i + 1;
              const active = page === pageNum;

              return (
                <Box
                  key={pageNum}
                  onClick={() => setPage(pageNum)}
                  sx={{
                    minWidth: 32,
                    height: 32,
                    px: 1,
                    borderRadius: "8px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    cursor: "pointer",
                    fontSize: "13px",
                    fontWeight: 600,
                    background: active
                      ? "linear-gradient(to bottom right, #393B8B, #AD78D2)"
                      : "transparent",
                    color: active ? "#fff" : "#374151",
                    boxShadow: active
                      ? "0 4px 12px rgba(79,70,229,0.25)"
                      : "none",
                    "&:hover": {
                      background: active
                        ? "linear-gradient(to bottom right, #2f3175, #9f63c7)"
                        : "#E5E7EB",
                    },
                  }}
                >
                  {pageNum}
                </Box>
              );
            })}

            {/* NEXT */}
            <Box
              onClick={() => page < totalPages && setPage(page + 1)}
              sx={{
                px: 2,
                py: "6px",
                borderRadius: "8px",
                cursor: page === totalPages ? "not-allowed" : "pointer",
                color: page === totalPages ? "#9CA3AF" : "#374151",
                fontSize: "13px",
                fontWeight: 500,
                "&:hover": {
                  backgroundColor:
                    page === totalPages ? "transparent" : "#E5E7EB",
                },
              }}
            >
              Next
            </Box>
          </Box>
        </Box>
      </Paper>
    </Box>
  );
}

export default GeneratedDocumentSection;