import React, { useEffect, useState } from "react";
import { Box, Typography, Paper, IconButton, Chip, Pagination } from "@mui/material";
import InsertDriveFileOutlinedIcon from "@mui/icons-material/InsertDriveFileOutlined";
import VisibilityOutlinedIcon from "@mui/icons-material/VisibilityOutlined";
import DownloadOutlinedIcon from "@mui/icons-material/DownloadOutlined";
import CheckCircleOutlineIcon from "@mui/icons-material/CheckCircleOutline";
import { FiEdit } from "react-icons/fi";
import { useNavigate } from "react-router-dom";
import { toCamelCase } from "../../../utils/textFormat.js";

import ROUTES from "../../../core/constants/routes.constant";
import ApiService from "../../../core/services/api.service";
import ServerUrl from "../../../core/constants/serverURL.constant";

function GeneratedDocumentSection() {
  const navigate = useNavigate();
  const api = new ApiService();

  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const rowsPerPage = 10;

  // 🔥 Fetch documents from backend
  const fetchDocuments = async (currentPage = 1) => {
    try {
      setLoading(true);

      const res = await api.apiget(
        `${ServerUrl.API_ALL_DOCUMENTS}?page=${currentPage}`
      );

      console.log("API RESPONSE:", res);

      // ✅ Correct mapping based on your API
      const docs = res?.data || [];
      const totalPages = res?.pages || 1;

      const normalizedDocs = docs.map((item) => ({
        ...item,
        employeeName: toCamelCase(item.employeeName),
        company: toCamelCase(item.company),
        issuedTo: toCamelCase(item.issuedTo),
      }));

      setDocuments(normalizedDocs);
      setTotalPages(totalPages);

    } catch (error) {
      console.error("Error fetching documents:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDocuments(page);
  }, [page]);

  return (
    <Box sx={{ width: "100%", mt: 4 }}>
      <Typography
        sx={{
          fontSize: "20px",
          fontWeight: 600,
          color: "#1F2937",
          mb: 3,
        }}
      >
        Today’s generated documents
      </Typography>

      <Paper
        sx={{
          borderRadius: "16px",
          boxShadow: "0px 20px 50px rgba(0,0,0,0.06)",
          overflow: "hidden",
        }}
      >
        <Box sx={{ overflowX: "auto" }}>
          <Box sx={{ minWidth: 1100 }}>
            {/* Header */}
            <Box
              sx={{
                display: "grid",
                gridTemplateColumns: "2fr 1.4fr 1.4fr 1.2fr 1fr 1fr 1fr",
                backgroundColor: "#ebecf9",
                px: 4,
                py: 2,
                fontSize: "13px",
                fontWeight: 500,
                color: "#6B7280",
              }}
            >
              <Box>Document Type</Box>
              <Box>Employee</Box>
              <Box>Company</Box>
              <Box>Generated by</Box>
              <Box>Date</Box>
              <Box>Status</Box>
              <Box textAlign="center">Actions</Box>
            </Box>

            {/* 🔥 Loading */}
            {loading && (
              <Box sx={{ p: 4, textAlign: "center" }}>Loading documents...</Box>
            )}

            {/* 🔥 No Data */}
            {!loading && documents.length === 0 && (
              <Box sx={{ p: 4, textAlign: "center" }}>No documents found</Box>
            )}

            {/* 🔥 Dynamic Rows */}
            {!loading &&
              documents.map((item, index) => (
                <Box
                  key={index}
                  onClick={() =>
                    navigate(ROUTES.USERDOCUMENT_DETAIL, {
                      state: {
                        id: item._id,
                        type: item.documentType,
                      },
                    })
                  }
                  sx={{
                    display: "grid",
                    gridTemplateColumns: "1.8fr 1.4fr 1.4fr 1.2fr 1fr 1fr 1fr",
                    px: 4,
                    py: 3,
                    alignItems: "center",
                    borderTop: "1px solid #F1F1F4",
                    cursor: "pointer",
                    "&:hover": {
                      backgroundColor: "#f9fafb",
                    },
                  }}
                >
                  {/* Document Type */}
                  <Box sx={{ width: "100%", display: "flex", alignItems: "center", gap: 2 }}>
                    <Box
                      sx={{
                        width: 40,
                        height: 40,
                        borderRadius: "12px",
                        background:
                          "linear-gradient(to bottom right, #393B8B, #AD78D2)",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        color: "#fff",
                      }}
                    >
                      <InsertDriveFileOutlinedIcon fontSize="small" />
                    </Box>

                    <Box>
                      <Typography sx={{ fontSize: "14px", fontWeight: 500 }}>
                        {item.documentType || "Document"}
                      </Typography>
                      {/* <Typography sx={{ fontSize: "12px", color: "#9CA3AF" }}>
                        {item.size || "—"}
                      </Typography> */}
                    </Box>
                  </Box>

                  {/* Employee */}
                  <Box>
                    <Typography sx={{ fontSize: "14px", fontWeight: 500 }}>
                      {item.employeeName || item.employee || "—"}
                    </Typography>
                    <Typography sx={{ fontSize: "12px", color: "#9CA3AF" }}>
                      {item.employeeId || item.id || "—"}
                    </Typography>
                  </Box>

                  {/* Company */}
                  <Typography sx={{ fontSize: "14px" }}>
                    {item.company
                      ? item.company.split(" ").slice(0, 3).join(" ")
                      : "—"}
                  </Typography>

                  {/* Generated By */}
                  <Typography sx={{ fontSize: "14px" }}>
                    {item.issuedTo || "—"}
                  </Typography>

                  {/* Date */}
                  <Typography sx={{ fontSize: "14px" }}>
                    {item.createdAt
                      ? new Date(item.createdAt).toLocaleDateString("en-US", {
                        month: "short",
                        day: "numeric",
                        year: "numeric",
                      })
                      : item.date || "—"}
                  </Typography>

                  {/* Status */}
                  <Box>
                    <Chip
                      icon={
                        <CheckCircleOutlineIcon
                          sx={{
                            backgroundColor: "#DCFCE7",
                            fontSize: 18, color: "#15803D"
                          }}
                        />
                      }
                      label={item.paymentStatus || "Completed"}
                      sx={{
                        backgroundColor: "#DCFCE7",
                        color: "#15803D",
                        fontWeight: 500,
                        fontSize: "13px",
                        px: 1,
                        py: 0.5,
                        // borderRadius: "999px", 
                        height: "36px",
                        "& .MuiChip-icon": {
                          marginLeft: "8px",
                        },
                        "& .MuiChip-label": {
                          paddingRight: "12px",
                        },
                      }}
                    />
                  </Box>

                  {/* Actions */}
                  <Box sx={{ display: "flex", justifyContent: "center", gap: 1 }}>

                    {/* Edit */}
                    <IconButton
                      onClick={(e) => e.stopPropagation()}
                      sx={{
                        backgroundColor: "#FEF3C7",
                        borderRadius: "12px",
                        width: 36,
                        height: 36,
                        "&:hover": {
                          backgroundColor: "#FDE68A",
                        },
                      }}
                    >
                      <FiEdit size={16} color="#D97706" />
                    </IconButton>

                    {/* View */}
                    <IconButton
                      onClick={(e) => e.stopPropagation()}
                      sx={{
                        backgroundColor: "#E0E7FF",
                        borderRadius: "12px",
                        width: 36,
                        height: 36,
                        "&:hover": {
                          backgroundColor: "#C7D2FE",
                        },
                      }}
                    >
                      <VisibilityOutlinedIcon sx={{ fontSize: 18, color: "#4F46E5" }} />
                    </IconButton>

                    {/* Download */}
                    <IconButton
                      onClick={(e) => e.stopPropagation()}
                      sx={{
                        backgroundColor: "#DCFCE7",
                        borderRadius: "12px",
                        width: 36,
                        height: 36,
                        "&:hover": {
                          backgroundColor: "#BBF7D0",
                        },
                      }}
                    >
                      <DownloadOutlinedIcon sx={{ fontSize: 18, color: "#16A34A" }} />
                    </IconButton>
                  </Box>
                </Box>
              ))}

            <Box sx={{ display: "flex", justifyContent: "center", mt: 3 }}>
              <Pagination
                count={totalPages}
                page={page}
                onChange={(e, value) => setPage(value)}
                sx={{
                  "& .MuiPaginationItem-root": {
                    borderRadius: "10px",
                    fontWeight: 500,
                  },

                  // 🔥 Selected page (gradient circle)
                  "& .Mui-selected": {
                    background: "linear-gradient(to bottom right, #393B8B, #AD78D2)",
                    color: "#fff",
                  },

                  "& .Mui-selected:hover": {
                    background: "linear-gradient(to bottom right, #2f3175, #9f63c7)",
                  },
                }}
              />
            </Box>
          </Box>
        </Box>
      </Paper>
    </Box>
  );
}

export default GeneratedDocumentSection;